// ============================================================
// 都道府県データ（全47件）
//   id: JISコード（地図SVGの data-code と数値一致で照合。ゼロ埋め2桁）
//   capitalDiffers: 県名と県庁所在地の漢字表記が異なる県（Step5で重点出題予定）
// ============================================================
"use strict";

window.PREFECTURES = [
  { id: "01", name: "北海道", reading: "ほっかいどう", region: "北海道", capital: "札幌", capitalReading: "さっぽろ", capitalDiffers: true },
  { id: "02", name: "青森県", reading: "あおもり", region: "東北", capital: "青森", capitalReading: "あおもり", capitalDiffers: false },
  { id: "03", name: "岩手県", reading: "いわて", region: "東北", capital: "盛岡", capitalReading: "もりおか", capitalDiffers: true },
  { id: "04", name: "宮城県", reading: "みやぎ", region: "東北", capital: "仙台", capitalReading: "せんだい", capitalDiffers: true },
  { id: "05", name: "秋田県", reading: "あきた", region: "東北", capital: "秋田", capitalReading: "あきた", capitalDiffers: false },
  { id: "06", name: "山形県", reading: "やまがた", region: "東北", capital: "山形", capitalReading: "やまがた", capitalDiffers: false },
  { id: "07", name: "福島県", reading: "ふくしま", region: "東北", capital: "福島", capitalReading: "ふくしま", capitalDiffers: false },
  { id: "08", name: "茨城県", reading: "いばらき", region: "関東", capital: "水戸", capitalReading: "みと", capitalDiffers: true },
  { id: "09", name: "栃木県", reading: "とちぎ", region: "関東", capital: "宇都宮", capitalReading: "うつのみや", capitalDiffers: true },
  { id: "10", name: "群馬県", reading: "ぐんま", region: "関東", capital: "前橋", capitalReading: "まえばし", capitalDiffers: true },
  { id: "11", name: "埼玉県", reading: "さいたま", region: "関東", capital: "さいたま", capitalReading: "さいたま", capitalDiffers: true },
  { id: "12", name: "千葉県", reading: "ちば", region: "関東", capital: "千葉", capitalReading: "ちば", capitalDiffers: false },
  { id: "13", name: "東京都", reading: "とうきょう", region: "関東", capital: "東京", capitalReading: "とうきょう", capitalDiffers: false },
  { id: "14", name: "神奈川県", reading: "かながわ", region: "関東", capital: "横浜", capitalReading: "よこはま", capitalDiffers: true },
  { id: "15", name: "新潟県", reading: "にいがた", region: "中部", capital: "新潟", capitalReading: "にいがた", capitalDiffers: false },
  { id: "16", name: "富山県", reading: "とやま", region: "中部", capital: "富山", capitalReading: "とやま", capitalDiffers: false },
  { id: "17", name: "石川県", reading: "いしかわ", region: "中部", capital: "金沢", capitalReading: "かなざわ", capitalDiffers: true },
  { id: "18", name: "福井県", reading: "ふくい", region: "中部", capital: "福井", capitalReading: "ふくい", capitalDiffers: false },
  { id: "19", name: "山梨県", reading: "やまなし", region: "中部", capital: "甲府", capitalReading: "こうふ", capitalDiffers: true },
  { id: "20", name: "長野県", reading: "ながの", region: "中部", capital: "長野", capitalReading: "ながの", capitalDiffers: false },
  { id: "21", name: "岐阜県", reading: "ぎふ", region: "中部", capital: "岐阜", capitalReading: "ぎふ", capitalDiffers: false },
  { id: "22", name: "静岡県", reading: "しずおか", region: "中部", capital: "静岡", capitalReading: "しずおか", capitalDiffers: false },
  { id: "23", name: "愛知県", reading: "あいち", region: "中部", capital: "名古屋", capitalReading: "なごや", capitalDiffers: true },
  { id: "24", name: "三重県", reading: "みえ", region: "近畿", capital: "津", capitalReading: "つ", capitalDiffers: true },
  { id: "25", name: "滋賀県", reading: "しが", region: "近畿", capital: "大津", capitalReading: "おおつ", capitalDiffers: true },
  { id: "26", name: "京都府", reading: "きょうと", region: "近畿", capital: "京都", capitalReading: "きょうと", capitalDiffers: false },
  { id: "27", name: "大阪府", reading: "おおさか", region: "近畿", capital: "大阪", capitalReading: "おおさか", capitalDiffers: false },
  { id: "28", name: "兵庫県", reading: "ひょうご", region: "近畿", capital: "神戸", capitalReading: "こうべ", capitalDiffers: true },
  { id: "29", name: "奈良県", reading: "なら", region: "近畿", capital: "奈良", capitalReading: "なら", capitalDiffers: false },
  { id: "30", name: "和歌山県", reading: "わかやま", region: "近畿", capital: "和歌山", capitalReading: "わかやま", capitalDiffers: false },
  { id: "31", name: "鳥取県", reading: "とっとり", region: "中国", capital: "鳥取", capitalReading: "とっとり", capitalDiffers: false },
  { id: "32", name: "島根県", reading: "しまね", region: "中国", capital: "松江", capitalReading: "まつえ", capitalDiffers: true },
  { id: "33", name: "岡山県", reading: "おかやま", region: "中国", capital: "岡山", capitalReading: "おかやま", capitalDiffers: false },
  { id: "34", name: "広島県", reading: "ひろしま", region: "中国", capital: "広島", capitalReading: "ひろしま", capitalDiffers: false },
  { id: "35", name: "山口県", reading: "やまぐち", region: "中国", capital: "山口", capitalReading: "やまぐち", capitalDiffers: false },
  { id: "36", name: "徳島県", reading: "とくしま", region: "四国", capital: "徳島", capitalReading: "とくしま", capitalDiffers: false },
  { id: "37", name: "香川県", reading: "かがわ", region: "四国", capital: "高松", capitalReading: "たかまつ", capitalDiffers: true },
  { id: "38", name: "愛媛県", reading: "えひめ", region: "四国", capital: "松山", capitalReading: "まつやま", capitalDiffers: true },
  { id: "39", name: "高知県", reading: "こうち", region: "四国", capital: "高知", capitalReading: "こうち", capitalDiffers: false },
  { id: "40", name: "福岡県", reading: "ふくおか", region: "九州", capital: "福岡", capitalReading: "ふくおか", capitalDiffers: false },
  { id: "41", name: "佐賀県", reading: "さが", region: "九州", capital: "佐賀", capitalReading: "さが", capitalDiffers: false },
  { id: "42", name: "長崎県", reading: "ながさき", region: "九州", capital: "長崎", capitalReading: "ながさき", capitalDiffers: false },
  { id: "43", name: "熊本県", reading: "くまもと", region: "九州", capital: "熊本", capitalReading: "くまもと", capitalDiffers: false },
  { id: "44", name: "大分県", reading: "おおいた", region: "九州", capital: "大分", capitalReading: "おおいた", capitalDiffers: false },
  { id: "45", name: "宮崎県", reading: "みやざき", region: "九州", capital: "宮崎", capitalReading: "みやざき", capitalDiffers: false },
  { id: "46", name: "鹿児島県", reading: "かごしま", region: "九州", capital: "鹿児島", capitalReading: "かごしま", capitalDiffers: false },
  { id: "47", name: "沖縄県", reading: "おきなわ", region: "九州", capital: "那覇", capitalReading: "なは", capitalDiffers: true },
];
